### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Aghits** [FallDownTheSystem/ChessBotPy#1]
Initialized TTS
[WinError 3] The system cannot find the path specified: 'eco'
Could not load eco files. Make sure there's an 'eco' folder in the root with these files: https://github.com/niklasf/eco
No section: 'gui'
Could not open engine. Please fix engine_path in settings.ini and try again.

Already corrected engine_path but still show this

**Comment by FallDownTheSystem** [comment]
Sounds to me like you're in the wrong directory when trying to run it. You have to be in the root directory, not the chessbotpy one.

**Comment by Aghits** [comment]
It works now thank you.
