### ISSUE TITLE
'int' object has no attribute 'score'

### ISSUE THREAD

**Issue by prolitornandbasturtrumerthydempe** [FallDownTheSystem/ChessBotPy#16]
I keep getting:
```
Something went wrong. Keep trying...
'int' object has no attribute 'score'
```

And then the analysis fails and can't keep track of the game.

It usually happens in the end game when I'm completely winning (the evaluation of all lines before this happens is really high, like 5000+).

**Comment by FallDownTheSystem** [comment]
I pushed a fix for this. This is what happens when you don't test your code 😄

**Comment by prolitornandbasturtrumerthydempe** [comment]
> I pushed a fix for this. This is what happens when you don't test your code 😄

Thanks. It works well :)
