### ISSUE TITLE
Overlapping arrows problem (pic)

### ISSUE THREAD

**Issue by prolitornandbasturtrumerthydempe** [FallDownTheSystem/ChessBotPy#17]
It is black to move:

[https://imgur.com/cdGA3b6](https://imgur.com/cdGA3b6)

The best move for black isn't being shown.
The best move for black is rook takes queen. I'm guessing there's an issue with overlapping arrows?

**Comment by FallDownTheSystem** [comment]
The arrow is drawn underneath, they're not fully opaque, so you can see a subtle color change where the arrows overlap. I could lower the opacity, but technically it's not an issue.
