### ISSUE TITLE
Whats is the best settings?

### ISSUE THREAD

**Issue by Twinsell** [FallDownTheSystem/ChessBotPy#18]
I tried to defeat the bot but couldn’t figure out which settings would allow me to play the game in the best way.

**Comment by Twinsell** [comment]
I tried to defeat the bot but couldn’t figure out which settings would allow me to play the game in the best way.

**Comment by FallDownTheSystem** [comment]
The higher you set the limits the more time the engine can use to think and the better the play will be. You can also improve performance by tweaking the engine settings so it can use as many cores and as much RAM as possible. Opening books and end game tables will also help. I wrote more about those in the github page's README.

Note that strongest play is very easily detected, and can get you banned.
