### ISSUE TITLE
Initial blur event is detectable 

### ISSUE THREAD

**Issue by prolitornandbasturtrumerthydempe** [FallDownTheSystem/ChessBotPy#20]
Chess dot com and Lichess both detect when the user's browser window loses focus (blur).
At the moment, when starting a game, the chess window loses focus and the ChessBotPy UI takes the focus immediately.

I'm not sure to what level they log this information, but they might see instant loss of window focus as suspicious over time, especially if it has a consistent timing.

Maybe allow the webUI window to take the background and to not take the focus immediately?

**Comment by FallDownTheSystem** [comment]
If you know how to do this in Chrome, let me know.
