### ISSUE TITLE
cant run on source code ..while the exe build is working or maybe because of my python version 3.7

### ISSUE THREAD

**Issue by epoyx44** [FallDownTheSystem/ChessBotPy#23]
i download the exe app on release 10 and it works fine.. but when it comes to source code i cant see the board in the css tab and it said ..something error try again.. its pretty wierd

**Comment by FallDownTheSystem** [comment]
Try to download a version of an engine that is compatible with your hardware. You can read the FAQ for more info.

**Comment by FallDownTheSystem** [comment]
Or try a later version of python
