### ISSUE TITLE
UCI Engine Integration

### ISSUE THREAD

**Issue by Simpion** [FallDownTheSystem/ChessBotPy#3]
> Initialized TTS
> Loading eco file: eco\a.tsv
> Loading eco file: eco\b.tsv
> Loading eco file: eco\c.tsv
> Loading eco file: eco\d.tsv
> Loading eco file: eco\e.tsv
> <UciProtocol (pid=12580)>: stderr >>        _
> <UciProtocol (pid=12580)>: stderr >> |   _ | |
> <UciProtocol (pid=12580)>: stderr >> |_ |_ |_| v0.25.1+git.69105b4 built Apr 30 2020
> Looking for connections...
> Client connected /b10ef735-d37f-4905-b8ed-2521aac8f1e3
> Error in connection handler
> Traceback (most recent call last):
>   File "lib\site-packages\websockets\server.py", line 191, in handler
>   File "main.py", line 376, in connection_handler
>   File "main.py", line 295, in send_engine_settings
>   File "lib\site-packages\chess\engine.py", line 1479, in __getitem__
> KeyError: 'debug log file'

I replaced the stockfish.exe with lc0.exe and the necessary dependencies for lc0 to run but there seems to be code that suggests this project only runs with stockfish and not other uci-compliant engines. What modifications can I make to make it work with lc0?

**Comment by FallDownTheSystem** [comment]
I just tested and there's a bug where it generates the engine settings file based on what was previously openened, so delete your lc0.ini file, make sure the engine path is set to lc0 and then restart and itll generate the correct engine settings.

**Comment by FallDownTheSystem** [comment]
I pushed a new version to master. The python script can now generate a settings file it if it is missing, a game can be started without setting an engine path, so you can still use it with opening books. It will now also re-send all the engine settings to the client if you set or change engine after already running the program.

This should help.

I'm still going to look into the engine hanging forever when there's an engine error (e.g. when lc0 looks for the weight in a path that does not exist), as well as when the engine runs for a really long time (e.g. when depth was set to high and no limit on time)

**Comment by FallDownTheSystem** [comment]
I just released version 5. This should improve the user experience when changing engines / updating settings.
