### ISSUE TITLE
SF NNUE network not loading.

### ISSUE THREAD

**Issue by Simpion** [FallDownTheSystem/ChessBotPy#30]
Guess I’ll leave it here for reference since the comment on the push request was closed. SF NNUE uses the isready command to initialize its network and load it in. Having all engines run the isready command every time the engine is opened and about to be used wouldn’t affect functionality or performance as it is a command used in all UCI engines and doesn’t take any processing time or power. This would solve the issue of SF NNUE performing without its network when using it as an engine.

**Comment by FallDownTheSystem** [comment]
I think it sends the isready command when it starts analysis by default, if it hasn't sent it yet. It is manually possible to send it via
`game.engine._isready()`  though.

I'm not familiar with SF NNUE. Is the problem that it'sn ever initializing its network or that its doing it too late?

**Comment by Simpion** [comment]
I assumed it was the lack of running isready but it might not be. When I use SF NNUE the network just doesn’t load, the binary works but I can tell the network isn’t loaded since it suggests moves a3 b3 c3 and so on regardless of position.

**Comment by Simpion** [comment]
You can find the binary on github from nod chip and a net from Sergio Vieri’s website.

**Comment by FallDownTheSystem** [comment]
I'm not too interested in trying it and trying to find out why it doesn't work. If you can find out the reason for the NN not running then I can try to fix it. 

If you think it's the isready command, then you can try adding  `game.engine._isready()` to start_engine or even in run_engine if you want to run every time, just for the purpose of trying it out.

**Comment by Simpion** [comment]
All right I’ll try that at report back.

**Comment by Simpion** [comment]
Placing game.engine._isready() between line 91 and 92 on main.py shouldn’t break anything and would run the command on start correct? Or do I also need to edit other parts of the script?

**Comment by FallDownTheSystem** [comment]
It should be fine. If it does crash it should be handled and it would just continue on anyway.

**Comment by Simpion** [comment]
Actually I looked into it and it seems that SF NNUE also loads it’s network with the UCInewgame command which should be the same as Lc0 but do you know when the current code runs that command?

**Comment by FallDownTheSystem** [comment]
Ill take a look at supporting the latest versions of Stockfish, haven't tested the NNUE yet.

**Comment by Simpion** [comment]
The latest Stockfish builds include NNUE now. The problem I was experiencing was just occurring because I was using a binary that was for a different CPU. I thought it was strange that the NNUE wasn’t loading when it loads the same way as LC0.

**Comment by FallDownTheSystem** [comment]
Yeah, tested with latest stockfish and everything works fine. Next release will include updated stockfish.
