### ISSUE TITLE
Wrong pieces detected moving

### ISSUE THREAD

**Issue by iamabigdogtoday** [FallDownTheSystem/ChessBotPy#36]
The day before I posted this, things are working fine. Then something happened

Here's the video of my gameplay at chess.com. Did the same thing on another newly formatted PC and the same results happen. In lichess, the arrows don't move at all and pieces don't move in the css window. Tried the same thing in Chrome/Opera/Edge, same result. Used both the ChessBotPy.js in the version 12 as well as the newer ChessBotPy.js 

https://youtu.be/bdkKXdxafws

Here is another one that shows the prompt. Shows something illegal with FEN:

https://youtu.be/m2pL1TB-KUk

ChessBotPy works properly if playing while signed out at chess.com. The videos above happen while I'm signed in.

My settings
Browser: Firefox 79
---------Violentmonkey, just copied and pasted the script from ChessBotPy.js

Other settings
![chess](https://user-images.githubusercontent.com/69671048/90230108-9e6bcd80-de4b-11ea-8744-b2ab2dfb9bfd.png)

Thanks for your awesome work.

**Comment by FallDownTheSystem** [comment]
You're probably using figurines in the Piece Notation (in Board and Pieces settings). Only text is supported at the moment.

**Comment by iamabigdogtoday** [comment]
It works now as well as lichess. Thanks.
