### ISSUE TITLE
Pieces Not Being Detected (Lichess)

### ISSUE THREAD

**Issue by ReverseNoob** [FallDownTheSystem/ChessBotPy#37]
Pieces are not being detected when moved in lichess
it was working fine till yesterday but today the detection has completely stopped even after updating pip and the bot

**Comment by epoyx44** [comment]
its because the chessbotpy.js is not updated just tweak it a little bit and it works fine..

**Comment by ReverseNoob** [comment]
Can you provide a modified one?

**Comment by FallDownTheSystem** [comment]
Seems Lichess is updating the html every few days

**Comment by FallDownTheSystem** [comment]
Fix on master
