### ISSUE TITLE
Engine Keeps Dying

### ISSUE THREAD

**Issue by ReverseNoob** [FallDownTheSystem/ChessBotPy#38]
Engine keeps dying with the error "<UciProtocol (pid=7336)>: stderr >> NNUE evaluation used, but the network file nn-112bb1c8cdb5.nnue was not loaded successfully. These network evaluation parameters must be available, and compatible with this version of the code. The UCI option EvalFile might need to specify the full path, including the directory/folder name, to the file. The default net can be downloaded from: https://tests.stockfishchess.org/api/nn/nn-112bb1c8cdb5.nnue" 

even with use nnue disabled in options

**Comment by ReverseNoob** [comment]
Error with lc0- <UciProtocol (pid=4660)>: Unexpected engine output: error The blas backend requires a network file.
<UciProtocol (pid=4660)>: stderr >> Creating backend [blas]...

**Comment by FallDownTheSystem** [comment]
Specify the path for the file. I had to add engine/ before the file name since I put the file in the engine folder
