### ISSUE TITLE
It stops registering moves after a while

### ISSUE THREAD

**Issue by botist** [FallDownTheSystem/ChessBotPy#5]
After playing a few moves against the chess.com computer (also happens against players), it just stops registering the moves, and when this happens the "Invalid SAN value" message always appears. I'm using Windows 10, Violentmonkey, and Google Chrome. The release I'm using is your latest at the moment I posted this. I'm using mostly default settings.

https://imgur.com/a/IMIwHGc
The chessbotpy.exe log:
Initialized TTS
Loading eco file: eco\a.tsv
Loading eco file: eco\b.tsv
Loading eco file: eco\c.tsv
Loading eco file: eco\d.tsv
Loading eco file: eco\e.tsv
Waiting for connections...
Client connected /f1c92c65-9a8b-4df9-95bb-eb42970fea14
Sending settings to client
Initializing engine settings file
Sending engine settings to client
Best move: e4
Best move: c5
Best move: d4
Best move: Nf6
Best move: Nc3
Invalid SAN value
Best move: Nc3
Invalid SAN value
Invalid SAN value
Best move: Nc3

**Comment by FallDownTheSystem** [comment]
The problem is that it doesn’t understand the notation when it’s not in English, if you change the language in chess.com, it should work.

**Comment by botist** [comment]
Oh I see, thank you
