### ISSUE TITLE
Analysis Opens GUI, Tactics Possibility?

### ISSUE THREAD

**Issue by Simpion** [FallDownTheSystem/ChessBotPy#6]
The user script usually bring up the web GUI when doing an analysis of a game on both lichess and chess.com. Could this be disabled or fixed through edits on the .js file?  Also do you think it could be possible to have the bot function on the tactics puzzles on lichess and chess.com?

**Comment by FallDownTheSystem** [comment]
Yes, you can edit the match metadata in the userscript
https://wiki.greasespot.net/Metadata_Block#.40match
https://developer.chrome.com/extensions/match_patterns

I'll probaby fix this at some point.

**Comment by FallDownTheSystem** [comment]
Also it should work on lichess tactics but not on chess.com because they dont show the moves.

**Comment by FallDownTheSystem** [comment]
GUI being opened on analysis pages should be fixed now. Bot functioning on chess.com puzzles might happen in the future, it's in my list of ideas.
